### PR TITLE
Notifications - Adapting to new design

### PR DESCRIPTION
**Pull request by tonysaad**
@fragsalat Actually your design was there still in `scss` but somehow the ws-notifications.scss in `components` was re-implementing all the styles again.

**I've taken out all the styles from here, and left it whole in `components` repo, as the styles need to be there only if the component is used**

I took out the animation onClick, as it was causing problems.
screen shot 2017-03-29 at 16 08 34

### CODE REVIEW

**Comment by schluchter** [comment]
@tonysaad Please use the icon 'cross' for the red notification.

**Comment by tonysaad** [comment]
Cross Icon
screen shot 2017-03-29 at 16 21 45

**Comment by schluchter** [comment]
@myueksel Please have a look at the vertical spacings. It seems like the Notification header and text could use a little more breathing space.

**Comment by schluchter** [comment]
@tonysaad 👍

**Comment by fragsalat** [comment]
Looks good to me but what problems did you have withe the animations?
I think think the notifications doesn't feel so good when they just appear without any movement.

**Comment by tonysaad** [comment]
@fragsalat The animation of sliding when appearing is still there, I've only took out the animation onClick which is for hiding.

I took the hiding animation out as it wasn't implemented right, and was causing problems more than it's being a good animation for 2 reasons:

1- There was this `marginBottom: -4.5rem` which was set to move the previous notification to the bottom after setting the opacity to Zero...this margin was causing the one underneath to look bad (see screenshot)
screen shot 2017-03-30 at 10 09 45

2- After user clicks we had to take out this `notification` from the `notifications` array in state, which would automatically removed the element from the DOM that's why we had this timeout to setState after 1 second to have this animation running before we do so (Which is really bad, as the timeout didn't work in some cases which lead the component to have `notifications` in the state but not visible elements because we had to maintain this reset of the timeout)

I think the animation should be implemented separately in a better way, ex. using shouldComponentUpdate to not update the DOM after hiding or maybe using a pure CSS solution but I still don't have the full idea in my head...what do you think ?

**Comment by tonysaad** [comment]
I've taken out all the styles from here, and left it whole in components repo, as the styles need to be there only if the component is used

**Pull request merged**
