### PR TITLE
fix(switch): fixed for firefox

### PR DESCRIPTION
**Pull request by antnascimento**
#106
Fix for displaying switch correctly on Firefox.

### CODE REVIEW

**Comment by szafranek** [comment]
Adding a label:
```
<input id="sample-checkbox" type="checkbox" className="mod-switch"/>
<label className="label1" htmlFor="sample-checkbox">On/Off</label>
```
makes the switch appear correctly in Firefox. I suggest updating the documentation and make it clear that `label` is now required.

However, the PR breaks support for wrapping the checkbox with a label instead of using the `for` attribute. This is a second, [valid](https://www.w3.org/TR/html5/forms.html#labeled-control) way of associating a label with input. It was working before.

Additionally, regular checkboxes still appear smaller in FF than Chrome.

**Comment by fragsalat** [comment]
@szafranek The correct way is described in the styleguide. Every other implementation is legacy and should be updated when you gonna use a new version :)
The label beside a checkbox was required also before because the is no toggle without text :D

**Comment by szafranek** [comment]
👍

**Comment by fragsalat** [comment]
But this one only changed it for the switch. Why not for radio and check boxes as well?

**Comment by antnascimento** [comment]
I will try to push the changes for the radio later

**Pull request merged**
