### PR TITLE
Reduce Y-offset so arrow tip remains visible

### PR DESCRIPTION
**Pull request by schluchter**
image

### CODE REVIEW

**Comment by faboweb** [comment]
The bottom shadow looks pretty long now. But fine for me. Plz comment/approve @wholesale-design-system/engineers @wholesale-design-system/ux

**Comment by myueksel** [comment]
It looks for me, that paper shadow 3 is used in this example. 
Please use Paper shadow 2.

**Comment by schluchter** [comment]
@faboweb I did use the wrong shadow. With the correct shadow, the arrow tip isn't visible because the offset isn't big enough (see pic 1). Increasing the offset on the shallower shadow looks crappy.  Can we change the way the arrow is generated so that it casts a shadow of its own? At the moment, only the rectangular container casts a shadow, and the tip depends on the offset and blur of the container for visibility.

Pic 1: image

Pic 2: 
image

**Comment by faboweb** [comment]
@tonysaad could you help here?

**Comment by faboweb** [comment]
#32 in here I implemented a arrow that throws it's on shadow. Still it is effected by the shadow from the other box... would be a trade-of solution

**Comment by faboweb** [comment]
As we defined this in the week-picker and defined a new shadow for hoverings, we close this PR.

**Pull request closed without merging**
